# SPDX-FileCopyrightText: © 2023 Dominik George <nik@naturalnet.de>
#
# SPDX-License-Identifier: LGPL-3.0-or-later

pipeline:
  test:
    group: test
    image: debian:bookworm
    commands:
      - apt-get -y update && apt-get -y install python3-poetry
      - poetry install --with test -E server -E cli
      - poetry run pytest
  build-docs:
    group: build
    image: debian:bookworm
    commands:
      - apt-get -y update && apt-get -y install python3-poetry
      - poetry install --with docs
      - poetry run sphinx-build -b html docs docs/_build/html
  deploy-docs-pages:
    group: deploy
    when:
      branch: main
    image: debian:bookworm
    secrets: [ACCESS_TOKEN]
    commands:
      - apt-get -y update && apt-get -y install git rsync
      - git config --global user.email "mail@ci.codeberg.org"
      - git config --global user.name "Codeberg CI"
      - git clone https://"$${ACCESS_TOKEN}"@codeberg.org/Vocata/pages-docs.git /pages
      - rsync -r --delete --exclude-from="docs/.rsyncignore" docs/_build/html/ docs/.domains docs/README.md docs/LICENSE /pages
      - cd /pages
      - git add -A
      - git commit -m "Generate website - based on commit ${CI_COMMIT_SHA}"
      - git push origin main
