# SPDX-FileCopyrightText: © 2023 Dominik George <nik@naturalnet.de>
#
# SPDX-License-Identifier: LGPL-3.0-or-later

pipeline:
  test:
    group: test
    image: debian:bookworm
    commands:
      - apt-get -y update && apt-get -y install python3-poetry
      - poetry install --with test -E server -E cli
      - poetry run pytest
  build-docs:
    group: build
    image: alpine
    commands:
      - apk add zola git
      - git submodule update --init --recursive
      - cd docs/; zola build; cd ..
  deploy-docs-pages:
    group: deploy
    when:
      branch: main
    image: alpine
    secrets: [ACCESS_TOKEN]
    commands:
      - apk add git rsync
      # configure git
      - git config --global user.email "mail@ci.codeberg.org"
      - git config --global user.name "Codeberg CI"
      # deploy changes
      - git clone https://"$${ACCESS_TOKEN}"@codeberg.org/Vocata/pages-docs.git /pages
      - rsync -r --delete --exclude-from="docs/.rsyncignore" docs/public/ docs/.domains docs/README.md docs/LICENSE /pages
      - cd /pages
      - git add -A
      - git commit -m "Generate website - based on commit ${CI_COMMIT_SHA}"
      - git push origin main
