pipeline:
  build:
    image: alpine
    commands:
      - apk add zola git
      - git submodule update --init --recursive
      - cd docs/; zola build; cd ..
  deploy:
    image: alpine
    secrets: [ACCESS_TOKEN]
    commands:
      - apk add git rsync
      # configure git
      - git config --global user.email "mail@ci.codeberg.org"
      - git config --global user.name "Codeberg CI"
      # deploy changes
      - git clone https://"$${ACCESS_TOKEN}"@codeberg.org/Vocata/pages-docs.git /pages
      - rsync -r --delete --exclude-from="docs/.rsyncignore" docs/public/ docs/.domains docs/README.md docs/LICENSE /pages
      - cd /pages
      - git add -A
      - git commit -m "Generate website - based on commit ${CI_COMMIT_SHA}"
      - git push origin main
