# SPDX-FileCopyrightText: © 2023 Dominik George <nik@naturalnet.de>
#
# SPDX-License-Identifier: LGPL-3.0-or-later

---
version: '3.4'

services:
  vocata:
    image: ${VOCATA_IMAGE:-vocata}:${VOCATA_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8044:8044"
