site_name: Vocata
site_url: https://docs.vocata.one

plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/stable/objects.inv
            - https://rdflib.readthedocs.io/en/stable/objects.inv
  - mermaid2
