[tool.poetry]
name = "vocata"
version = "0.1.0"
description = "Vocabulary Agnostic Transport Agent"
authors = ["Dominik George <nik@naturalnet.de>"]
license = "LGPL-3.0-or-later"
readme = "README.md"
homepage = "https://vocata.one/"
repository = "https://codeberg.org/Vocata/vocata"
keywords = ["activitypub", "fediverse"]

[tool.poetry.dependencies]
python = "^3.10"
rdflib = "^6.3.2"
pyld = "^2.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
